### PR TITLE
Fix #307 Add custom properties to vra_fabric_network resource and dat…

### LINKED ISSUE #307: Unable to create on-demand network profile against a new NSX-T cloud account
**vRA version**
8.3
**Terraform version**
0.14.6 (observed on 0.13 also)
**terraform-provider-vra plugin version**
0.3.4

**Describe the bug**
When creating a network profile to create an on-demand network with NSX-T.  If the NSX-T manager is added as a cloud account in the same apply as the network profile creation, the profile creation fails to find the network domain created as part of a data filter.

A second apply correctly creates the network profile.

**To Reproduce**
https://github.com/sentania/vraPrivateCloudDemo/tree/devel
See networkprofile.tf and ondemandnetworkprofile module definition.

**Expected behavior**
The network profile should be created as specified using a newly added cloud account.

**Screenshots**

**Logs**
Attach logs to help debug the issue
1. Attach vra-terraform.log
2. Attach Terraform console log (Enable terraform logs following the steps mentioned in https://www.terraform.io/docs/configuration/environment-variables.html)
3. crash.log(if any)

**Desktop (please complete the following information):**

**Additional context**

image

### PR DESCRIPTION
**Pull request by dondon3345678**
Fix #307 Add custom properties to vra_fabric_network resource and data resource.

Signed-off-by: Daniel Chuang <tchuang@vmware.com>

### CODE REVIEW

File: vra/data_source_fabric_network.go [hunk 1]
```diff
@@ -70,6 +70,10 @@ func dataSourceFabricNetwork() *schema.Resource {
 				Type:     schema.TypeString,
 				Computed: true,
 			},
+			"custom_properties": {
```
Comment (Prativa20) [inline vra/data_source_fabric_network.go:73]: Please add this property in the doc https://github.com/vmware/terraform-provider-vra/blob/master/website/docs/d/fabric_network.html.markdown

File: vra/resource_fabric_network_vsphere.go [hunk 2]
```diff
@@ -109,6 +109,10 @@ func resourceFabricNetworkVsphere() *schema.Resource {
 				Type:     schema.TypeString,
 				Computed: true,
 			},
+			"custom_properties": {
+				Type:     schema.TypeMap,
+				Computed: true,
```
Comment (Prativa20) [inline vra/resource_fabric_network_vsphere.go:114]: The custom property is optional when creating the zone. Please refer swagger doc. So, it will be both computed and optional true

**Review by Prativa20 — APPROVED** [review]
looks good!
